# Generated by Django 3.1.5 on 2021-01-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidates',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('contact_no', models.PositiveIntegerField()),
                ('age', models.PositiveIntegerField()),
                ('recent_company', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('current_ctc', models.CharField(max_length=20)),
                ('fixed_component_in_ctc', models.CharField(max_length=20)),
                ('work_experience', models.CharField(max_length=100)),
                ('work_6_days_a_week', models.BooleanField()),
                ('willing_to_relocate_mumbai', models.BooleanField()),
                ('verbal_eng_skill_rate', models.PositiveIntegerField()),
                ('skills_you_have_worked', models.CharField(max_length=100)),
                ('industry_you_have_worked', models.CharField(max_length=100)),
                ('profile_you_like_to_work', models.CharField(max_length=100)),
                ('matters_most_while_selecting_job', models.CharField(max_length=100)),
                ('latest_resume', models.DateField()),
            ],
        ),
    ]
