# Generated by Django 3.1.5 on 2021-01-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_handling_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='candidates',
            name='work_experience_in_months',
            field=models.CharField(default='Null', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidates',
            name='skills_you_have_worked',
            field=models.CharField(max_length=200),
        ),
    ]
