# Generated by Django 3.1.5 on 2021-01-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_handling_app', '0005_auto_20210109_0955'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auth_user',
        ),
    ]
